language: node_js
node_js:
  - "15.2.1"
dist: xenial  
sudo: required
services:
  - docker

env:
  global:
    - DOCKER_TLS_VERIFY="1"
    - DOCKER_HOST="tcp://40.8.140.149:2376"
    - DOCKER_CERT_PATH="./azure"
    - DOCKER_MACHINE_NAME="dronuts2021-team-3"

script:
  - (cd backend && npm install && npm test)
  - (cd frontend && npm install && npm test)
  - docker-compose build

deploy:
  skip_cleanup: true
  provider: script
  script: docker-compose up -d --remove-orphans
  on:
    branch: master
