language: node_js
node_js:
  - "15.2.1"
dist: xenial  
sudo: required
services:
  - docker

env:
  global:
    - DOCKER_TLS_VERIFY="1"
    - DOCKER_HOST="tcp://13.93.209.83:2376"
    - DOCKER_CERT_PATH="./azure"
    - DOCKER_MACHINE_NAME="dronuts2021-team-3"
    - YARN_GPG=no

install:
  - npm install
script:
  - npm run lint
  - (cd backend && npm test)
  - (cd frontend && npm test)

deploy:
  skip_cleanup: true
  provider: script
  script: 
  - docker-compose build --force-rm
  - docker-compose up -d --force-recreate --remove-orphans
  on:
    branch: main