version: '3'
services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres,
      POSTGRES_PASSWORD: team3dronuts!,
      POSTGRES_DB: postgres,

  dronuts:
    container_name: dronuts2021-team-3
    build: ./
    ports:
      - "80:3000"
    restart: always
